```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("helper_functions/exploratory_analysis.R")
```

```{r}
h1b_df <- read.csv("clean_data/h1b_FY2021_FY2024.csv")
```

## How does the win rate vary by country? 

```{r}
country_code_mapping <- list(CAN = "Canada", 
                             CHN = "China", 
                             GBR = "United Kingdom", 
                             IND = "India", 
                             KOR = "South Korea", 
                             MEX = "Mexico", 
                             NPL = "Nepal", 
                             PAK = "Pakistan", 
                             PHL = "Philippines", 
                             TWN = "Taiwan", 
                             SGP = "Singapore", 
                             CHL = "Chile")

bump_plot(h1b_df, "country_code", "Countries", "won_lottery", "Lottery Win Rates", 10, country_code_mapping, "Certain Countries Look Like They Have An Advantage In The H-1B Visa Lottery")
```

## How does the multiple registration rate vary by country? 

```{r}
bump_plot(h1b_df, "country_code", "Countries", "had_multiple_regs", "Multiple Registration Rates", 10, country_code_mapping, "Certain Countries Have Higher Multiple Registration Rates In The H-1B Visa Lottery")
```

## How does the win rate vary by company? 

```{r}
company_mapping <- list(`Amazon.com Services LLC` = "Amazon Services", 
                             `Google LLC` = "Google", 
                             `Microsoft Corporation` = "Microsoft", 
                             `Capgemini America, Inc.` = "Capgemini", 
                             `Tata Consultancy Services Limited` = "Tata", 
                             `HCL America Inc` = "HCL", 
                             `Cognizant Technology Solutions US Corp` = "Cognizant", 
                             `IBM Corporation` = "IBM", 
                             `IBM Corp` = "IBM", 
                             `Infosys Limited` = "Infosys", 
                             `Accenture LLP` = "Accenture", 
                             `Wipro Limited` = "Wipro", 
                             `WIPRO LIMITED` = "Wipro", 
                             `Mindtree Limited` = "LTIMindtree", 
                             `MindTree Limited` = "LTIMindtree", 
                             `LTIMINDTREE LIMITED` = "LTIMindtree", 
                             `Meta Platforms, Inc.` = "Meta", 
                             `Facebook, Inc.` = "Meta", 
                             `Tech Mahindra Americas Inc` = "Tech Mahindra", 
                             `Tech Mahindra Americas Inc.` = "Tech Mahindra")


bump_plot(h1b_df, "employer_name", "Companies", "won_lottery", "Lottery Win Rates", 10, company_mapping, 
          "Certain Companies Look Like They Have An Advantage In The H-1B Visa Lottery")
```

## How does the multiple registration rate vary by company? 

```{r}
# note: when I plotted raw multiple registration rates instead of ranks, these companies tended to have below-average multiple registration rates

bump_plot(h1b_df, "employer_name", "Companies", "had_multiple_regs", "Multiple Registration Rates", 10, company_mapping, "Multiple Registration Rates By Company Fluctuate Considerably Across Years")
```

## How does the win rate vary by age? 

```{r}
line_plot(h1b_df, "age_in_years", "Age", "won_lottery", "Win", 21, 50, "25-30 Year Olds Look Like They Have An Advantage in the H-1B Visa Lottery")
```

## How does the multiple registration rate vary by age? 

```{r}
line_plot(h1b_df, "age_in_years", "Age", "had_multiple_regs", "Multiple Registration", 21, 50, "Multiple Registration Rates Vary By Age")
```

## How high are lottery win rates among H-1B1 visa countries? 

```{r}
h1b1_df <- h1b_df %>%
  filter(country_code %in% c("SGP", "CHL")) %>%
  mutate(country_code := recode(country_code, !!!country_code_mapping)) %>%
  group_by(lottery_year, country_code) %>%
  summarise(win_rate = sum(won_lottery)/n(), n_obs = n())

ggplot(h1b1_df, aes(x = lottery_year, y = win_rate))+
  geom_bar(stat = "identity")+
  expand_limits(y = c(0, 0.55))+
  labs(x = "Lottery Year", y = "Win Rate", title = "H-1B1 Visa Applicants Don't Seem To Have Lottery Advantage", subtitle = "These applicants should have 100% lottery win rates given existing quotas.")+
  geom_text(aes(label = glue("{round(100*win_rate, 0)}%\n(n={n_obs})")), vjust = -0.1)+
  facet_wrap(~country_code)+
  scale_y_continuous(labels = scales::percent_format())+
  theme_minimal()
```


